name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: shark-trendz
  REGION: europe-southwest1
  REPOSITORY: mage-data-prep
  IMAGE_NAME: mageai

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login Docker to Google Artifact Registry
      uses: 'docker/login-action@v1'
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}
        username: _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Apply Terraform Docker Registry
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
      run: |
        cd terraform
        terraform apply -auto-approve -input=false -target=google_artifact_registry_repository.my_docker_repo -target=google_service_account.docker_pusher -target=google_artifact_registry_repository_iam_member.docker_pusher_iam

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Apply Terraform
      run: |
        cd terraform
        echo '${{ secrets.GCP_CREDENTIALS }}' > /tmp/gcp_credentials.json
        terraform apply -auto-approve -input=false
        rm -f /tmp/gcp_credentials.json
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
        TF_VAR_docker_image_tag: '${{ github.sha }}'
        TF_VAR_service_account_key_file: '/tmp/gcp_credentials.json'