name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: shark-trendz
  REGION: europe-southwest1
  REPOSITORY: mage-data-prep
  IMAGE_NAME: mageai

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Artifact Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Apply Terraform
      run: |
        cd terraform
        terraform apply -auto-approve
